services:
  configserver:
    build:
      context: .
      dockerfile: ./ConfigServer/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: "file:/config-repo"

  eureka:
    build:
      context: .
      dockerfile: eureka/Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - configserver
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8888


  clientmanagment:
    build:
      context: .
      dockerfile: ClientManagment/Dockerfile
    depends_on:
      - configserver
      - eureka
      - db
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8888
      - SPRING_PROFILES_ACTIVE=docker
    ports:
<<<<<<< HEAD
=======
      # мапиш ТІЛЬКИ якщо хочеш ходити з хоста напряму
>>>>>>> ce92d58fb9c581b1b8206c89b2c21f6f98f5b812
      - "8080:8080"

  ordermanagment:
    build:
      context: .
      dockerfile: OrderMangment/Dockerfile
    depends_on:
      - configserver
      - eureka
      - db
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8888
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"

  productincartmanagment:
    build:
      context: .
      dockerfile: ProductInCartManagment/Dockerfile
    depends_on:
      - configserver
      - eureka
      - db
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8888
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"

  productmanagment:
    build:
      context: .
      dockerfile: ProductManagment/Dockerfile
    depends_on:
      - configserver
      - eureka
      - db
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8888
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"

<<<<<<< HEAD
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - clientmanagment
      - ordermanagment
      - productincartmanagment
      - productmanagment

=======
>>>>>>> ce92d58fb9c581b1b8206c89b2c21f6f98f5b812
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:




