spring:
  application:
    name: ordermanagment

  config:
    import: optional:configserver:http://configserver:8888

  cloud:
    discovery:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
  endpoint:
    health:
      show-details: always
eureka:
  client:
    enabled: false