spring.application.name=ClientManagment
spring.datasource.url=jdbc:postgresql://localhost:5432/clients_db
spring.datasource.username=postgres
spring.datasource.password=admin

deliver-classs-name=org.postgresql.Driver
spring.password.driver-class-name
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
