apiVersion: v2
name: microservices5
description: Helm chart for Microservices5 Kubernetes manifests
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 18.5.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
